### ISSUE TITLE
Vote anonymity is not always ensured

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#5]
# Problem

- After a vote, if the employee is not found or the manager is not found, the vote is never anonymized
- After a vote, if sending the email to the manager fails (retries included), the vote is never anonymized.
- After a vote, if the update command to anonymize the vote fails (retries included), the vote is never anonymized.

# Proposed solution

Implement #4 then use the technique described in "Proposed solution to communicate success".

**Comment by Ked57** [comment]
Possible ideas: 
- Run a cron task that calls a cloud that checks every night the last x hrs votes and ensure they're anonymized.
- Create a new collection "toAnonymize" where we put votes ids as document id and a boolean "anonymized" + possibly a timestamp to trace when it has been done. Then we run a cloud fonction ever x hrs to check and correct it too.

I personaly prefer the first one because of it's simplicity but i might be missing something

**Comment by hgwood** [comment]
I like my proposed solution more ^^

**Comment by hgwood** [comment]
#4 is implemented now.

**Comment by hgwood** [comment]
I can't find any code that anonymise votes, so I'm not sure what we were talking about. If one day we want to implement anonymity, we'll start from scratch.
